#!/bin/bash

start_app() {
  cd "$1" && nohup "$2" > /dev/null 2>&1 &
  echo "Started $2 in $1"
}

start_app /root/Desktop/pay/ wine vzopaysys.exe 
sleep 3
start_app /home/server/gw/Goodess KG_Goodess
sleep 3
start_app /home/server/gw/Bishop KG_Bishop
sleep 3
start_app /home/server/gw/Relay SO2RelayD
sleep 3
start_app /home/server/gs0/ SO2GameSrvD0
sleep 3
start_app /home/server/gs1/ SO2GameSrvD1
sleep 3
start_app /home/server/gs2/ SO2GameSrvD2
sleep 3
start_app /home/server/gs3/ SO2GameSrvD3
sleep 3
start_app /home/server/gs4/ SO2GameSrvD4
sleep 3
start_app /home/server/gs5/ SO2GameSrvD5
sleep 3
start_app /home/server/gs6/ SO2GameSrvD6
