#!/bin/bash

# Hàm để chạy server và in thông báo hoàn thành
run_server() {
  local dir=$1
  local server=$2

  cd "$dir" || exit 1 # Kiểm tra thư mục, thoát nếu lỗi
  ./"$server" &       # Chạy server ở chế độ nền
  echo "$server đã chạy xong"
}

# Chạy các server
run_server "/home/server/gw/Goddess" "KG_GoddessD"
sleep 10
run_server "/home/server/gw/Bishop" "KG_BishopD"
sleep 10
run_server "/home/server/gw/Relay" "SO2RelayD"
sleep 10
run_server "/home/server/gs0" "SO2GameSvrD0"
sleep 10
run_server "/home/server/gs1" "SO2GameSvrD1"
sleep 10
run_server "/home/server/gs2" "SO2GameSvrD2"
sleep 10
run_server "/home/server/gs3" "SO2GameSvrD3"
sleep 10
run_server "/home/server/gs4" "SO2GameSvrD4"
sleep 10
run_server "/home/server/gs5" "SO2GameSvrD5"
sleep 10
run_server "/home/server/gs6" "SO2GameSvrD6"
